#!/bin/bash
# this line worked when this was just a text file, but I reset ruby versions JUUUUST often enough
# to make turning this into a script worth it
# grep -v '#' gems_i_always_want.txt | xargs gem install
function gem_list {
    echo coderay \
         colorize \
         columnize \
         debug \
         deep_merge \
         dicks \
         faraday \
         figlet \
         irb \
         json \
         lolcat \
         nokogiri \
         nyan \
         optimist \
         pry \
         pry-byebug \
         rack \
         rake \
         serve \
         term-ansicolor \
         text-table \
         thin
}

echo "gem_list | xargs gem install"
gem_list | xargs gem install
